FROM php:8.3-cli-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    libgd-dev \
    libmbstring-dev \
    libintl-dev \
    libcurl4-openssl-dev \
    libssh2-1-dev \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install gd curl ssh2

COPY candy-vcr/fonts/*.ttf /usr/local/share/fonts/
RUN fc-cache -f /usr/local/share/fonts/

WORKDIR /home/sites/sugarcraft
